name: prometheus_scrape
version: 0
status: published
lib: charms.prometheus_k8s.prometheus_scrape
summary: Configure Prometheus scraping jobs.
description: |
  The `prometheus_scrape` interface supports configuring Prometheus scrape jobs and recording and alerting rules.
  The provider specifies one or more scrape compatible metrics endpoints, and rule files.
  The requirer then scrapes the provider's metrics and emits alerts per rule files.

providers:
  - name: prometheus-k8s
    url: https://www.github.com/canonical/prometheus-k8s-operator
  - name: loki-k8s
    url: https://www.github.com/canonical/loki-k8s-operator
  - name: grafana-k8s
    url: https://www.github.com/canonical/grafana-k8s-operator
  - name: prometheus-scrape-config-k8s
    url: https://www.github.com/canonical/prometheus-scrape-config-k8s-operator
  - name: prometheus-scrape-target-k8s
    url: https://www.github.com/canonical/prometheus-scrape-target-k8s-operator
  - name: alertmanager-k8s
    url: https://www.github.com/canonical/alertmanager-k8s-operator
  - name: zinc-k8s
    url: https://github.com/jnsgruk/zinc-k8s-operator

requirers:
  - name: prometheus-k8s
    url: https://www.github.com/canonical/prometheus-k8s-operator
  - name: grafana-agent-k8s
    url: https://www.github.com/canonical/grafana-agent-k8s-operator

maintainer: observability
