name: prometheus_remote_write
version: 0
status: published
lib: charms.prometheus_k8s.prometheus_remote_write
summary: Write Prometheus metrics to remote endpoint.
description: |
  The `prometheus_remote_write` endpoint supports writing Prometheus metrics to a remote endpoint.
  The provider publishes one or more endpoints.
  The requirer pushes metrics to the provided endpoints.

providers:
  - name: prometheus-k8s
    url: https://www.github.com/canonical/prometheus-k8s

requirers:
  - name: grafana-agent-k8s
    url: https://www.github.com/canonical/grafana-agent-k8s

maintainer: observability

