name: Test publish 'charmlibs-pathops' package
on:
  workflow_dispatch:

jobs:
  lint:
    uses: ./.github/workflows/lint.yaml
  tests:
    uses: ./.github/workflows/tests.yaml
    with:
      package: pathops
  build-n-publish:
    name: Build and Publish 'charmlibs-pathops' to Test PyPI
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      attestations: write
      contents: read
    needs: [lint, tests]
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v6
      - name: Build
        run: uv build
        working-directory: ./pathops
      - name: Attest build provenance
        uses: actions/attest-build-provenance@v2.4.0
        with:
          subject-path: 'pathops/dist/*'
      - name: Publish
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: ./pathops/dist/
          repository-url: https://test.pypi.org/legacy/
